  # Enable admin page
  # IMPORTANT: Activate HTTPS before enabling this feature, to avoid possible MITM attacks.
  # Reference: https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-admin-page
{% raw %}
  token: "{{ vault.bitwarden.token }}"
{% endraw %}
  signups_allowed: {{ bitwarden.signups_allowed  | default(vault.bitwarden.signups_allowed, None) | default('true') }}
  # Only allow signups from certain domains (set signups_allowed to "false")
  # Note that no e-mail validation is done, only e-mail domain that's provided on registration
  # Can be a single entry "example.com", or multiple comma separated: "example.com,example.net,example.org"
  signups_domains_whitelist: {{ bitwarden.signups_domains_whitelist  | default(vault.bitwarden.signups_domains_whitelist, None) | default(False) }}
