---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Create necessary folders, with appropriate permissions.
  file:
    path: "{{ volumes_root }}/nextcloud/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  with_items:
    - "apps"
    - "config"
    - "webroot"
    - "themes"

- name: Start {{service_item}}
  include: includes/start.yml
